<?xml version="1.0" encoding="UTF-8" ?>
<customtestsuite errors="1" failures="1" customname="com.zutubi.pulse.core.commands.core.JUnitReportPostProcessorTest" tests="3" customtime="0.391">
  <properties>
    <property name="ivy.dep.file" value="ivy.xml"></property>
  </properties>
  <customtestcase classname="com.zutubi.pulse.core.commands.core.JUnitReportPostProcessorTest" customname="testSimple" customtime="0.291"></customtestcase>
  <customtestcase classname="com.zutubi.pulse.core.commands.core.JUnitReportPostProcessorTest" customname="testFailure" customtime="0.01">
    <customfailure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at
        com.zutubi.pulse.core.commands.core.JUnitReportPostProcessorTest.testFailure(JUnitReportPostProcessorTest.java:63)
    </customfailure>
  </customtestcase>
  <customtestcase classname="com.zutubi.pulse.core.commands.core.JUnitReportPostProcessorTest" customname="testError" customtime="0.0">
    <customerror message="whoops!" type="java.lang.RuntimeException">java.lang.RuntimeException: whoops!
	at
        com.zutubi.pulse.core.commands.core.JUnitReportPostProcessorTest.testError(JUnitReportPostProcessorTest.java:68)
    </customerror>
  </customtestcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</customtestsuite>
